# Generated by Django 4.0.3 on 2022-03-31 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_signup', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisers',
            old_name='ad_id',
            new_name='ad_name',
        ),
    ]
