# Generated by Django 4.0.3 on 2022-03-31 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_signup', '0002_rename_ad_id_advertisers_ad_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisers',
            name='ad_name',
            field=models.CharField(max_length=255),
        ),
    ]
