# Generated by Django 4.0.3 on 2022-04-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_signup', '0003_alter_advertisers_ad_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisers',
            name='company_email',
            field=models.CharField(max_length=50),
        ),
    ]
