# Generated by Django 4.0.3 on 2022-03-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_signup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_email',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
