# Generated by Django 4.0.3 on 2022-04-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Purchase_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_phone', models.CharField(max_length=30)),
                ('company_email', models.CharField(max_length=50, unique=True)),
                ('ad_price', models.IntegerField()),
                ('ad_name', models.CharField(max_length=255)),
                ('purchase_date', models.DateField()),
            ],
        ),
    ]
