# Generated by Django 4.0.3 on 2022-04-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0002_user_purchase_list_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_purchase_list',
            name='user_email',
            field=models.CharField(default='potato@gmail.com', max_length=50),
            preserve_default=False,
        ),
    ]
