# Generated by Django 4.0.3 on 2022-04-27 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0004_user_purchase_list_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_purchase_list',
            name='active',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
