# Generated by Django 4.0.3 on 2022-04-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0005_user_purchase_list_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_purchase_list',
            name='dump',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
